### ISSUE TITLE
Color Crashing Ring

### ISSUE THREAD

**Issue by Treverr** [maxkonovalov/MKRingProgressView#11]
Hello,

I have two rings inside of a standard UIViewController, and when I add the second one it says 

"MKRingProgressView was compiled with optimization - stepping may behave oddly; variables may not be available."

When the app crashes.

Also, I am getting a error: IB Designables: Failed to render and update auto layout status for HomeViewController (h2x-s1-kZZ): The agent crashed

Any idea what could be causing this?

**Comment by Treverr** [comment]
I just have two different UIViews set as MKRingProgressview that causes the crash. Not inside of one another.

**Comment by Treverr** [comment]
It is crashing on this line:

`            self.init(r: UInt8((c?[0])! * 0xff), g: UInt8((c?[1])! * 0xff), b: UInt8((c?[2])! * 0xff), a: UInt8((c?[3])! * 0xff))`

in the MKGradientGenerator.swift file

**Comment by Treverr** [comment]
It looks like the Cyan color is crashing the ring actually

**Comment by maxkonovalov** [comment]
Hi @Treverr!
I was able to reproduce your issue by adding a single progress view in storyboard and assigning start/end colors (no matter what values) in View Attributes Inspector. So looks like it has something to do with the `@IBInspectable` properties. Leaving the "Default" values for these attributes in storyboard and setting the colors in code worked fine though, so I suggest you to use this workaround for now, while I look for a solution to fix this.
If you have any thoughts on this, please let me know.

**Comment by purpleblues** [comment]
This is due to the wide range of color from iOS10. Each CGColor component can have value bigger than 1.0 or smaller than 0.0. 

If you are ok with ignoring the wide range of color, you can use this initializer in `extension RGBA` in MKGradientGenerator.swift 

```Swift
fileprivate init(_ color: CGColor) {

        let c = color.components?.map({ (v) -> CGFloat in
            if v < 0.0 {
                return 0.0
            }else if v > 1.0 {
                return 1.0
            } else {
                return v
            }
        })

        switch color.numberOfComponents {
        case 2:
            self.init(r: UInt8((c?[0])! * 0xff), g: UInt8((c?[0])! * 0xff), b: UInt8((c?[0])! * 0xff), a: UInt8((c?[1])! * 0xff))
        case 4:
            self.init(r: UInt8((c?[0])! * 0xff), g: UInt8((c?[1])! * 0xff), b: UInt8((c?[2])! * 0xff), a: UInt8((c?[3])! * 0xff))
        default:
            self.init()
        }
    }

```

**Comment by jendaz** [comment]
@maxkonovalov @purpleblues solution fixes that issue. Could you add it into the code and cocoa pods?

**Comment by maxkonovalov** [comment]
@Treverr @purpleblues @jendaz 
Sorry guys for the delay, finally got my hands on the fix – should work without crashes now 🎉
Thanks @MariusCiocanel for the PR 😉

Please note that the current fix may cause some colors to be displayed incorrectly on wide-gamut screens due to clamped values.

Cheers!
