### ISSUE TITLE
Change number of rings

### ISSUE THREAD

**Issue by simonstewart** [maxkonovalov/MKRingProgressView#12]
Great component!

Is there an easy way to only show the outer ring? (i.e. not the 2 smaller inner rings).
Perhaps something like:
self.progressGroup.numberOfRings = 1

I'll then put a custom UIView in the middle.

**Comment by simonstewart** [comment]
Easy enough to modify the code, which I've done, but means we will have issues merging code fixes in future.

**Comment by maxkonovalov** [comment]
Hi @simonstewart!
The control itself represents a single ring, so if that's what you need, simply use the `MKRingProgressView` class directly. The `MKRingProgressGroupView` is there for demo purposes only - you can easily wrap the control in your own custom view like this one and customize it for your needs.
