### ISSUE TITLE
Statically update ring progress

### ISSUE THREAD

**Issue by HarshilShah** [maxkonovalov/MKRingProgressView#13]
I’d love to have the ability to update a ring’s progress without any animation. When displaying multiple rings in a single view controller, if you animate rings as they appear, you have to watch the animation multiple times as you scroll and that gets tiring, and if you try to instead animate them all at once, this can cause a drop in framerate. So being able to selecting statically update rings would be nice.

**Comment by maxkonovalov** [comment]
Hello @HarshilShah 
As the control is based on `CALayer`, you can adjust the animations like this:
```swift
CATransaction.begin()
CATransaction.setAnimationDuration(0.0)
ringProgressView.progress = 1.0
CATransaction.commit()
```
The code above should update the progress immediately without animation.

**Comment by HarshilShah** [comment]
That does the trick, thanks! Any suggestions on improving performance, btw? Added two rings to a view controller in `viewDidLoad`, and it adds a good 1–2 seconds of delay to the push animation.

**Comment by maxkonovalov** [comment]
Indeed, generating the gradient image can take some time, especially if the control is large. More on performance here: https://github.com/maxkonovalov/MKGradientView#performance

To speed the things up, in the line
```
_gradientImage = MKGradientGenerator.gradientImage(type: .conical, size: CGSize(width: r, height: r), colors: [endColor, endColor, startColor, startColor], locations: [0.0, s, (1.0 - s), 1.0], endPoint: CGPoint(x: 0.5 - CGFloat(2 * s), y: 1.0), scale: 1)
```
try changing `scale: 1` to some lower value that gives nice performance/quality ratio for you.

**Comment by HarshilShah** [comment]
Oh wow, setting the scale to 0.5 is exactly what I wanted. No lag, and it still looks just as good to my eyes. Thanks a lot! 🙌🏽

**Comment by maxkonovalov** [comment]
@HarshilShah you're welcome :)
I think I'll add a possibility to change the `scale` property in one of the future updates.
