### ISSUE TITLE
Main.storyboard: error: IB Designables: Failed to render and update auto layout status for *ViewController*: The agent crashed

### ISSUE THREAD

**Issue by epavlov** [maxkonovalov/MKRingProgressView#15]
Swift 3 code update needed.

In MKRingProgressView.swift file line 281 this: 
`let ctx = UIGraphicsGetCurrentContext()!`

needs to be wrapped in guard statement:
```
guard let ctx = UIGraphicsGetCurrentContext() else {
            return nil
        }
```
and change function to return optional CGImage:
`func contentImage() -> CGImage? {}`

**Comment by epavlov** [comment]
Additionally, on line 263 update function to:
```
    override open func display() {
        if let content = contentImage() {
            self.contents = content
        }
    }
```

**Comment by maxkonovalov** [comment]
Hi @epavlov! Thanks for pointing out this issue :)
I updated the code to use optional context. 
As for the `display()` func, `self.contents` is optional anyway, and when wrapped in `if let` clause, there might be issues like showing old contents. 
Let me know what you think

**Comment by maxkonovalov** [comment]
I'm closing this issue now due to inactivity.
@epavlov if you have any issues with the fix, please reopen it and let me know.
