### ISSUE TITLE
progress = 0  the circle there is a red dot

### ISSUE THREAD

**Issue by IAskWind** [maxkonovalov/MKRingProgressView#16]
RingProgressView.progress = 0 startColor, endColor set to red backgroundRingColor set to gray, but in the beginning of the circle there is a red dot, how to cancel this

**Comment by IAskWind** [comment]
如图
![image](https://cloud.githubusercontent.com/assets/17396956/23550969/c12586ce-004e-11e7-8f1f-b2423bcf2fcf.png)

**Comment by maxkonovalov** [comment]
This is by design – the dot filled with start color is always visible at 0%

**Comment by jayanaka** [comment]
progressGroup.ring1.hidesRingForZeroProgress = true
