### ISSUE TITLE
Progress not working

### ISSUE THREAD

**Issue by lancevalour** [maxkonovalov/MKRingProgressView#2]
When I set the progress to be 1.0, nothing changes. I am using the sample code as below and running on simulator.:
```swift
let ringProgressView = MKRingProgressView(frame: CGRect(x: 0, y: 100, width: 100, height: 100))
ringProgressView.startColor = UIColor.redColor()
ringProgressView.endColor = UIColor.magentaColor()
ringProgressView.ringWidth = 25
ringProgressView.progress = 1.0
view.addSubview(ringProgressView)
```

**Comment by maxkonovalov** [comment]
@lancevalour just copypasted the code above to my `viewDidLoad()` and it worked with no issues (the progress is set to full circle). Can you give some more details on your setup?

**Comment by lancevalour** [comment]
OK figure out. 

Because I put the ringProgressView in the viewController which is inside the tabBarController, if I set the progress in viewDidLoad(), it will not be set because onViewDidLoad() is called when viewController is added in tabBarController. If I set the progress in viewDidAppear() then it works.

You can close this right now. Thank you!

**Comment by maxkonovalov** [comment]
Great! I hope you enjoy using this control ;)
