### ISSUE TITLE
Swift 4 compatibility

### ISSUE THREAD

**Issue by jaymathew** [maxkonovalov/MKRingProgressView#23]
Current version installed by cocopods won't work in Xcode 9. It throws this error when building to a device "Module compiled with Swift 3.1 cannot be imported in Swift 4.0: "

**Comment by maxkonovalov** [comment]
@jaymathew did you try clean (clean build folder also), removing derived data and restarting Xcode 9?
More info here: https://stackoverflow.com/q/44399109/3160561

**Comment by jaymathew** [comment]
Clean & removing derived data did the trick.  thanks.
