### ISSUE TITLE
Following Manual Approach Not Working

### ISSUE THREAD

**Issue by breenjoe** [maxkonovalov/MKRingProgressView#27]
I'm trying to add MKRingProgressView to a test project.  I tried the manual approach which says "_Just add MKGradientGenerator.swift and MKRingProgressView.swift to your Xcode project._"

But adding just those to files to my project (and trying to use them) doesn't seem to be the entirety of what is needed to get this view available in an unrelated project.

**Comment by maxkonovalov** [comment]
Hello @breenjoe, I just tried adding the files to a new project and it worked fine. What are the exact issues that you have?

**Comment by breenjoe** [comment]
After adding MKGradientGenerator.swift and MKRingProgressView.swift files to my project I get an error when building that says "_No such module 'MKRingProgressView_" on the "import MKRingProgressView" statement in MKRingProgressGroupView.swift.  It seems like the MKRingProgressView class cannot be located or it's expecting a framework called MKRingProgressView.

**Comment by maxkonovalov** [comment]
No need to import the module, because you add the files to the same module of your main app. Just use the `MKRingProgressView` class straight away.
