### ISSUE TITLE
I know i am being dumb, but ...

### ISSUE THREAD

**Issue by clokey** [maxkonovalov/MKRingProgressView#28]
The readme says that the animation of the progress ring can be configured using CATransaction.setAnimationDuration, but I just can't seem to get it to work. I've just created a new single view application. copied the two swift files into it. Added a single view, with a custom class set to MKRingProgressView. Set the initial values using the IBDesignable values, and added:

```
    override func viewWillAppear(_ animated: Bool) {
        super.viewWillAppear(true)
        CATransaction.begin()
        CATransaction.setAnimationDuration(1.0)
        progressView.progress = 0.5
        CATransaction.commit()
        
    }
```

my expectation was that when the view was shown on screen it would animate the ring from 0.0 to 0.5 in the course of a second, but instead, the progress ring just appears with no animation.

What am I doing wrong? I looked at the example, but you seem to be using UIView. animate with a closure, to update a group of views, but I can't even get the simple case to work. Any pointers gratefully received. (Please be kind, I am getting back into iOS development and newish to Swift)

**Comment by maxkonovalov** [comment]
Hi @clokey!
The code you posted looks correct. My guess here is that in `viewWillAppear` it might be too early yet to start animations, did you try putting the same thing in `viewDidAppear`?
Also, are you sure that the progress is 0.0 when you start animation? Maybe it's already set to the final value somewhere, so the animation won't start.

**Comment by clokey** [comment]
Hi @maxkonovalov I move the code block to viewDidAppear and ensured that elsewhere there was an initial state set (rather than in the storyboard) and it correctly animated. Thanks for getting back to me!

**Comment by maxkonovalov** [comment]
You're welcome ;)
