### ISSUE TITLE
MKRingProgressGroup

### ISSUE THREAD

**Issue by iLandes** [maxkonovalov/MKRingProgressView#3]
Hello,

I'm just testing your code for a new app. Unfortunately class MKRingProgressGroupView and MKRingProgressGroupButton are not delivered with pod download. Any idea why ? Any solution ?

Thanks for reply
Regards
Seb

ps : please note I'm French and my english is so bad :-)

**Comment by maxkonovalov** [comment]
Hey Seb, these classes are there for demo purposes only and are not intended to be part of the control itself, that's why they are not included with the pod. Feel free to copy them to your project and modify to fit your needs if you like ;)

**Comment by maxkonovalov** [comment]
Thanks! I hope you enjoy using it :) If you have some questions feel free to ask ;)
