### ISSUE TITLE
Linking MKRingProgressView to objective-c project

### ISSUE THREAD

**Issue by StefanBouwer** [maxkonovalov/MKRingProgressView#31]
I have a framework that I have built myself, with its own podspec and one of its dependencies is MKRingProgressView. Note that my framework and the rest of its dependencies are written in objective-c.

`pod lib lint` does validate successfully with my framework's podspec, although whenever I do a pod install on another project with my framework, I get this error on the MKRingProgressView framework whenever I try to compile:

`The "Swift Language Version" (SWIFT_VERSION) build setting must be set to a supported value for targets which use Swift. This setting can be set in the build settings editor.`

Isn't it necessary that MKRingProgressView needs to specify the swift version in its podspec as well?

Also, it looks like a few of `open var` are not translated as properties when `MKRingProgressView-Swift.h` is imported out of an objective-c project. Adding the @objc attribute to these variables may fix it.

**Comment by maxkonovalov** [comment]
Hello @StefanBouwer,

There's no such setting as swift version in podspec. However, the lib has a `.swift-version` file as required. My guess is that the above error comes from somewhere else. I'd suggest you to try adding a `.swift-version` file to your framework that depends on swift framework, and also try adding MKRingProgressView pod directly to your main project to make sure it works there.

As for missing **@objc** attributes, I'll update the lib to make it compatible with objective-c, too ✌🏻

**Comment by StefanBouwer** [comment]
So we managed to add the MKRingProgressView pod as a dependency. And it works great now. Like you mentioned, the @objc attribute is still the only thing missing :).

Thanks a ton @maxkonovalov.

**Comment by maxkonovalov** [comment]
@StefanBouwer great! I'll let you know once I release an update.

**Comment by StefanBouwer** [comment]
Thanks man 👌.

**Comment by maxkonovalov** [comment]
@StefanBouwer, objc support is here 🎉
Please let me know if you have any issues.

**Comment by StefanBouwer** [comment]
@maxkonovalov Thanks a ton! This library is awesome btw 😝!

**Comment by maxkonovalov** [comment]
Thank you! 😀
