### ISSUE TITLE
Inconsistent speed

### ISSUE THREAD

**Issue by thijsheijden** [maxkonovalov/MKRingProgressView#33]
Hey! Im not sure this is supposed to be like this but when I find the speed at which the ring moves very inconsistent. If I put it on a timer of 60 seconds the first few seconds it will move very fast, but then slow down and the last 20 seconds it will be moving extremely slow. Is there any way I could make the animation of the ring one consistent speed?

**Comment by maxkonovalov** [comment]
Hi @thijsheijden, you need to set the animation curve to `linear`, like this:
```
CATransaction.setAnimationTimingFunction(CAMediaTimingFunction(name: kCAMediaTimingFunctionLinear))
```
Please see the related issue #32 for more information.

**Comment by thijsheijden** [comment]
Ah thanks!
