### ISSUE TITLE
iOS 12 BETA

### ISSUE THREAD

**Issue by emilpedersen** [maxkonovalov/MKRingProgressView#37]
iOS 12 BETA simulator gives this error:
`[Unknown process name] clip: empty path.`

It just draws a square.
<img width="51" alt="screenshot 2018-06-16 at 14 05 00" src="https://user-images.githubusercontent.com/3866442/41498443-4a767bd6-716e-11e8-8c6e-f58472e53521.png">

It's only when progress = 0

**Comment by maxkonovalov** [comment]
@emilpedersen should be fixed now, thank you!
