### ISSUE TITLE
Animating with UIViewPropertyAnimator

### ISSUE THREAD

**Issue by frogg** [maxkonovalov/MKRingProgressView#45]
I am trying to animate the `.progress` property witch works wonderful within a `UIView.animate` block.
I want to have control over the animation progress though, so I put it within a UIViewPropertyAnimator (so I can manipulate the `animator.fractionComplete` property). This doesn't seem to work. Is there something special to keep in mind for animating the `RingProgressView`?

**Comment by maxkonovalov** [comment]
Hi @frogg! Unfortunately, it is currently impossible to use `UIViewPropertyAnimator` for interactive animations on custom properties, because it relies on a private class `_UIViewAdditiveAnimationAction` instead of a regular `CABasicAnimation`. The only thing you can do is set `animator.isInterruptible = false`, but it eliminates the possibility to use `fractionComplete` etc.

You can check this thread for more info: https://twitter.com/nicklockwood/status/489379202056339458

**Comment by frogg** [comment]
Hey thanks a lot for the quick reply. That would've been too good to be true then 😣

But if I'm willing to use private API it's possible you say?
Why do you think – would implementing `_UIViewAdditiveAnimationAction` be a lot of work or just a few lines for me?

**Comment by maxkonovalov** [comment]
Seems not that hard in fact - if you take a look into runtime headers, you can see that `_UIViewAdditiveAnimationAction` has a `pendingAnimation` property, which should be the actual animation we're after. So you can grab it and use in the `action(forKey:)` of `RingProgressLayer` ✌️

**Comment by frogg** [comment]
That doesn't seem to be hard indeed 😍
Do you know by any chance how I can get the `_UIViewAdditiveAnimationAction ` object in `action(forKey event: String)`? 

I've tried with `super.action(forKey: event)` but I always receive `nil` there – except for when it's an `CABasicAnimation` (and this case is handled already anyway): 
`<CABasicAnimation:0x2821f4100; delegate = <UIViewAnimationState: 0x10dc29480>; fillMode = both; timingFunction = easeInEaseOut; duration = 1.2; fromValue = 1; keyPath = opacity>`

**Comment by maxkonovalov** [comment]
It is `nil` because it is optionally casted to `CABasicAnimation` - you need to modify the code to get any value from `super.action(forKey:)` and then if it is not a `CABasicAnimation`, try to check if it responds to selector `"pendingAnimation"` and get the actual animation using objc runtime.

**Comment by frogg** [comment]
Thanks a lot, Max!
Now, look at this 😍


![screenrecording_10-25-2018 16-46-48 2018-10-25 16_51_30](https://user-images.githubusercontent.com/5204169/47509380-44fd6d80-d876-11e8-8b19-37ccc329ffea.gif)

**Comment by maxkonovalov** [comment]
Awesome! Looks great 👏
