### ISSUE TITLE
Apple watch support

### ISSUE THREAD

**Issue by stephenhsklarew** [maxkonovalov/MKRingProgressView#47]
What are the plans for Apple watch support?  

In the meantime are there any workarounds or ports that will make this UI object work for Apple Watch?

Thank you!

- Stephen

**Comment by maxkonovalov** [comment]
Hi @stephenhsklarew! No plans to add Apple Watch support yet, but if you figure out the way to use the control on the watch, feel free to submit a pull request ;)

**Comment by stephenhsklarew** [comment]
Thanks @maxkonovalov! I can try doing it, but it's a bit beyond my skill level - it will take me much longer. Would this be something someone would be interested in doing for some money?

**Comment by maxkonovalov** [comment]
@stephenhsklarew actually there's currently no simple way to create a custom view on watchOS. But I would suggest two options to try:
- Use the native `WKInterfaceActivityRing`, it is the original progress rings from Apple Watch.
- Pre-generate a set of images and use them as an animated progress with `WKInterfaceImage`, the images can be generated here - http://hmaidasani.github.io/RadialChartImageGenerator/

**Comment by stephenhsklarew** [comment]
excellent, thank you!

*Stephen Sklarew*
Chief Executive Officer
stephen.sklarew@synaptiq.ai
949.413.8306
Schedule a meeting <https://calendly.com/stephen-sklarew>

<https://twitter.com/synaptiqai> <https://www.facebook.com/synaptiq>
<http://www.linkedin.com/>
<https://www.youtube.com/channel/UCydh4GkLsV8M14x-HRZVI9w>
<http://www.synaptiq.ai/>
_________________________________
