### ISSUE TITLE
Same startColor and endColor produces unnecessary gradient

### ISSUE THREAD

**Issue by xquezme** [maxkonovalov/MKRingProgressView#48]
I assume, this because library uses `!==` instead of `!=`, but `.cgColor` always produce different instance. And pointers are not equal.

<img width="257" alt="screenshot 2019-02-21 at 00 53 15" src="https://user-images.githubusercontent.com/814506/53127344-4401f180-3573-11e9-8e28-0303a48ba29c.png">

Example:
```swift
let view = RingProgressView()
view.startColor = .red
view.endColor = .red
```

Workaround:
```swift
let view = RingProgressView()
let color = UIColor.red.cgColor
let layer = (view.layer as! RingProgressLayer)
layer.startColor = color
layer.endColor = color
```

**Comment by maxkonovalov** [comment]
Yes, indeed, in some cases the check would produce incorrect result, I pushed a fix.
