### ISSUE TITLE
Edges are rough

### ISSUE THREAD

**Issue by mommyme** [maxkonovalov/MKRingProgressView#5]
You've done a great job on this but I wanted to let you know that the edges are a little rough in your drawing. The image looks fragmented. I don't know how to improve, but I just wanted to let you know.

**Comment by maxkonovalov** [comment]
Hello @mommyme! Thanks for noticing this, can you please check if the following line fixes the issue?
```swift
ringProgressView.allowsAntialiasing = true
```

**Comment by maxkonovalov** [comment]
The rough edges were caused because `allowsAntialiasing` was set to `false`. I updated the control to have the antialiasing enabled by default, so it should look good now 😀
