### ISSUE TITLE
HELP WANTED! Group rings don't work

### ISSUE THREAD

**Issue by MatuskaDevelopement** [maxkonovalov/MKRingProgressView#51]
I can't get the group rings working. One ring works perfectly, but when I make it RingProgressGroupView class it gives this error "Use of undeclared type 'RingProgressGroupView'". Please help, I am pretty new at Swift. This is my code:

import UIKit
import MKRingProgressView

class ViewController: UIViewController {
    
    @IBOutlet weak var ringView: RingProgressGroupView!  //This is where the error shows
    
    override func viewDidLoad() {
        super.viewDidLoad()
    }
}

**Comment by maxkonovalov** [comment]
Group rings are not included in the lib, and are only part of the demo. You need to copy the classes from the example to your own project.

**Comment by MatuskaDevelopement** [comment]
Thanks 

Odesláno z iPhonu

17. 4. 2019 v 19:17, Max Konovalov <notifications@github.com>:
