### ISSUE TITLE
Crash at gradientGenerator.image() 

### ISSUE THREAD

**Issue by voyage11** [maxkonovalov/MKRingProgressView#52]
This is the line that crash:-

let ctx = CGContext(data: &data, width: w, height: h, bitsPerComponent: bitsPerComponent, bytesPerRow: w * bytesPerPixel, space: colorSpace, bitmapInfo: bitmapInfo.rawValue)!

**Comment by voyage11** [comment]
Thread 1: Fatal error: Unexpectedly found nil while unwrapping an Optional value

I can see that w and h are 0.

**Comment by MarcoCarnevali** [comment]
I too have this problem

**Comment by pepejeria** [comment]
I started having this problem too. Worked well until recently.

**Comment by pepejeria** [comment]
I solved the crash by dragging the source files manually to the project. Removed library from the Pod-file and it all works fine now.

**Comment by maxkonovalov** [comment]
Hi guys, this is fixed in version [2.2.3](https://github.com/maxkonovalov/MKRingProgressView/releases/tag/2.2.3)
