### ISSUE TITLE
I get an CoreGraphics API error when using the RingProgressView

### ISSUE THREAD

**Issue by noahkamara** [maxkonovalov/MKRingProgressView#55]
Error: this application, or a library it uses, has passed an invalid numeric value (NaN, or not-a-number) to CoreGraphics API and this value is being ignored. Please fix this problem.

**Comment by maxkonovalov** [comment]
Hi @noahkamara, this should now be fixed in the [latest release](https://github.com/maxkonovalov/MKRingProgressView/releases/tag/2.2.3), please let me know if you still have any issues
