### ISSUE TITLE
Need update to Swift 2.3 

### ISSUE THREAD

**Issue by javo11** [maxkonovalov/MKRingProgressView#6]
If it is not updated to Swift 2.3 it won't work with Xcode 8.

**Comment by joekw** [comment]
After going through the 2.3 conversion process, my app will crash at line 236 of MKRingProgressView.swift

`        let p = (self.presentationLayer() as? MKRingProgressLayer)?.progress ?? 0.0
`

**Comment by maxkonovalov** [comment]
I'm currently updating the lib to swift 3, so these issues should be fixed soon.

**Comment by maxkonovalov** [comment]
@javo11 @joekw hey guys, please check out the [1.1](https://github.com/maxkonovalov/MKRingProgressView/releases/tag/1.1) release and let me know if you have any issues.
Unfortunately, I can't push these to cocoapods repo yet, because it has issues with validating swift 3 projects, but I'll try to update it asap.

**Comment by joekw** [comment]
Haven't updated my project to Swift 3 yet so I can't check (Crucial framework I'm using hasn't been updated yet). 

Don't suppose there's a quick fix for just Swift 2.3?

**Comment by maxkonovalov** [comment]
@joekw Try changing this line to the follownig:
```swift
let p = self.presentationLayer()?.progress ?? 0.0
```

**Comment by joekw** [comment]
Perfect, thanks!

**Comment by hishamabri** [comment]
Can you please push v1.1 spec to Cocoapods?
Still not available
https://github.com/CocoaPods/Specs/tree/66039f5d58d707afbfc270aeb89f9c03f2dd41f6/Specs/MKRingProgressView

**Comment by maxkonovalov** [comment]
Ok, finally got cocoapods to work with swift 3 😀
@javo11 @joekw @hishamabri the version 1.1 is now available via cocoapods 🎉
