### ISSUE TITLE
Recompile MKRingProgressView without delete-reinstall of 

### ISSUE THREAD

**Issue by Jimw338** [maxkonovalov/MKRingProgressView#60]
I have an app that uses MKRingProgressView (Loop diabetes app), and I want to get familiar with making changes to the code - and figure MKRingProgressView is a "easy" place to start.  Is there a way to recompile only the framework cod without xCode's "delete-then-reinstall" for the entire app?

Or at least without disrupting whatever resident information the app has left on iOS, actually.  I'm currently using the app, and if I delete it, it clears out the address information of the current insulin pod (Omnipod) is linked.

(This might not be the right forum to ask this)

**Comment by maxkonovalov** [comment]
@Jimw338 I don't quite understand if there is any problem with the lib, but for broader questions like issues with Xcode frameworks it is better to ask for help on [StackOverflow](https://stackoverflow.com)
