### ISSUE TITLE
Crashes on iOS 9 at initWithCoder

### ISSUE THREAD

**Issue by euroboy** [maxkonovalov/MKRingProgressView#64]
In **Crashlytics** I'm receiving a crash when loading a RingProgressView from storyboard. Crash is logged in initWithCoder with the following information:

```
EXC_BAD_ACCESS KERN_INVALID_ADDRESS 0x0000000000000010
Crashed: com.apple.main-thread
0  libobjc.A.dylib                0x181535b90 objc_msgSend + 16
1  UIKit                          0x18701eef8 -[UIView _createLayerWithFrame:] + 252
2  UIKit                          0x18701eb00 UIViewCommonInitWithFrame + 688
3  UIKit                          0x187325fb4 -[UIView initWithCoder:] + 304
4  MKRingProgressView             0x100b776e8 $s18MKRingProgressView04RingbC0C5coderACSgSo7NSCoderC_tcfcTf4gn_n + 72
5  MKRingProgressView             0x100b76fbc $s18MKRingProgressView04RingbC0C5coderACSgSo7NSCoderC_tcfcTo + 32
```

It happens only on iOS 9. Also I'm subclassing RingProgressView, if this may help.

**Comment by euroboy** [comment]
The problem may be that I'm subclassing RingProgressView. Trying without subclassing and will log the result.

**Comment by maxkonovalov** [comment]
Hi @euroboy, please check if you have any issues with the [latest release](https://github.com/maxkonovalov/MKRingProgressView/releases/tag/2.2.3)
