### ISSUE TITLE
SPM fails while resolving MKRingProgressView

### ISSUE THREAD

**Issue by SimonJanevski** [maxkonovalov/MKRingProgressView#65]
Hi

can you make a new release with the latest commits that will include the Package.swift? SPM currently fails with the message that it can't find the Package.swift. Making a new release seams to solve it.

Thanks, Simon

**Comment by maxkonovalov** [comment]
Hi @SimonJanevski, I pushed a new release [2.2.3](https://github.com/maxkonovalov/MKRingProgressView/releases/tag/2.2.3), please let me know if you have any issues.

**Comment by SimonJanevski** [comment]
Seams to be working now, thanks for the quick response and a great lib.
