### ISSUE TITLE
Using interface builder, how does one add a progress group

### ISSUE THREAD

**Issue by thexande** [maxkonovalov/MKRingProgressView#7]
Greetings. Amazing lib!

Your readme states: 

### Interface Builder
`MKRingProgressView` can be set up in Storyboard. Specify `startColor`, `endColor`, `ringWidth` and optional `backgroundRingColor` (if not set, defaults to `startColor` with 15% opacity).

However I cannot figure out how to add group container view, progress group to a new view controller in story board. How can I add your progress view as if I would add a label, button or other UI element?

I would like to add progress groups similar to the following example: 

![screen shot 2016-09-26 at 11 14 37 am](https://cloud.githubusercontent.com/assets/7704414/18844432/744d1dd0-83da-11e6-9910-657d9501a088.png)

THANKS!!

**Comment by maxkonovalov** [comment]
Hi @thexande! Thanks, I really appreciate that you like the lib 😀

To add the control in a storyboard, simply drag a UIView onto the canvas and in the Identity Inspector change its class to `MKRingProgressView` or `MKRingProgressGroupView` depending on which one you want to use:

<img width="259" alt="class" src="https://cloud.githubusercontent.com/assets/3026460/19215831/b125b382-8db9-11e6-880e-57bd5a22155e.png">

After that, all `IBInspectable` attributes will be available for setup.

Note that the `MKRingProgressGroupView` is for demo purposes only and is not distributed with cocoapods. If you want to use this class and are adding the control with cocoapods, just copy that file to your project and feel free to modify it as you like.

Hope this helps!

**Comment by thexande** [comment]
Thanks! It worked!
