### ISSUE TITLE
Pattern Image instead of Gradient

### ISSUE THREAD

**Issue by alex-de-waal** [maxkonovalov/MKRingProgressView#73]
Is there a way to swop the gradient with an image containing a pattern? Like in the below example

![Progress-Bars-with-Patterns](https://user-images.githubusercontent.com/60880336/106710187-35952f00-65fe-11eb-8261-afec5d6c882c.gif)

**Comment by maxkonovalov** [comment]
@alex-de-waal you can try using `UIColor(patternImage: <#UIImage#>)` for the `startColor` and `endColor` properties of the `RingProgressView`.

**Comment by alex-de-waal** [comment]
@maxkonovalov Oh nice, didn't even know about that. I'll give it a go. Thanks for the reply.

**Comment by alex-de-waal** [comment]
Many many thanks @maxkonovalov, it worked beautifully. We can close this issue 😄

**Comment by maxkonovalov** [comment]
You're welcome! 😉
