### ISSUE TITLE
swift 2.3 

### ISSUE THREAD

**Issue by gplsek** [maxkonovalov/MKRingProgressView#8]
Is there a version that will work with swift 2.3?

**Comment by maxkonovalov** [comment]
Hi @gplsek, sorry for the late response, I don't plan to support swift 2.3 currently. Swift 3 is available on the master branch, and for swift 2.2 pick the 1fe9a90a09ff8890e42bfbfc4d65e95b6baa4ef6 commit.

**Comment by gplsek** [comment]
Thank you Max, I think we sorted it out, thank you for providing the code!!
-george
