### ISSUE TITLE
Line with a squared-off end

### ISSUE THREAD

**Issue by cristinaITdeveloper** [maxkonovalov/MKRingProgressView#9]
I use your library adding it manually and change code to customize it for my needs.
I would have the progress line with a squared-off end, but changing 
_ctx.setLineCap(.square)_
 it doesn't work.
Can you help me?

**Comment by maxkonovalov** [comment]
Hello @cristinaITdeveloper!
Indeed, to make it work, changing the line cap isn't enough. Check out the branch `square-end` -> db40c9a081948a9a0ebed5dcec6dd93fff9b66c2, I tested this a little, seems to work fine.
Cheers

**Comment by cristinaITdeveloper** [comment]
Awesome, it's work fine! Thank you!

**Comment by maxkonovalov** [comment]
You're welcome :)
